baseURL = "/"
title = "Topal Metaverse"
languageCode = "en"
enableInlineShortcodes = true
theme = "soho"
summarylength = 10
enableEmoji = true
relativeUrls = true

[params]
author = "Topal"
description = ""

## Set one of:
# gravatar = "app16816@gmail.com"
profilePicture = "images/profile.png"

# copyright = "Author Name"
# license = "CC BY-SA 4.0"
# licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#CC9966"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.

  
  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/topal168"

  [[params.socialIcons]]
  icon = "fa-telegram"
  title = "Telegram"
  url = "https://t.me/xinguwan"

#  [[params.socialIcons]]
#  icon = "fa-linkedin"
#  title = "Linkedin"
#  url = "#"

  [[params.socialIcons]]
  icon = "fa-youtube"
  title = "Youtube"
  url = "https://www.youtube.com/channel/UCn0kzPvIugVXi7EknVdQaaQ"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/gitopal/"



[menu]

 # [[menu.main]]
 # name = "Posts"
 # weight = 100
 # identifier = "posts"
 # url = "/posts/"

 # [[menu.main]]
 # name = "About"
 # identifier = "about"
 # weight = 300
 # url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4